// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package doc

import (
	"github.com/gq-leon/go-pandoc/api/doc"
)

type ControllerV1 struct{}

func NewV1() doc.IDocV1 {
	return &ControllerV1{}
}
